 #!/usr/bin/env groovy
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing test..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying test....'
            }
        }
    }
}